import React, { useState } from 'react';
import { Language, ProjectData } from '../types';
import { X, Database, BarChart3, Code2, CheckCircle2, TrendingUp, ExternalLink, FolderGit2, Copy, Check } from 'lucide-react';

interface ProjectDetailModalProps {
  project: ProjectData | null;
  isOpen: boolean;
  onClose: () => void;
  language: Language;
}

export const ProjectDetailModal: React.FC<ProjectDetailModalProps> = ({
  project,
  isOpen,
  onClose,
  language
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'sql' | 'metrics' | 'impact'>('overview');
  const [copied, setCopied] = useState(false);

  if (!isOpen || !project) return null;

  // Custom project specific deep-dive content
  const deepDiveContent: Record<string, { sql: string; dax: string; kpiStats: { label: string; value: string; desc: string }[] }> = {
    'proj-1': {
      sql: `-- 1. Star Schema Revenue & Margin Cohort Aggregation
WITH RegionalCohort AS (
  SELECT 
    d.region_name,
    p.category_name,
    COUNT(DISTINCT f.order_id) AS order_volume,
    SUM(f.sales_amount) AS gross_revenue,
    SUM(f.profit_margin) AS gross_profit,
    ROUND(SUM(f.profit_margin) / NULLIF(SUM(f.sales_amount), 0) * 100, 2) AS profit_margin_pct,
    DENSE_RANK() OVER (PARTITION BY d.region_name ORDER BY SUM(f.sales_amount) DESC) AS rank_in_region
  FROM fact_sales f
  JOIN dim_geography d ON f.geo_id = d.geo_id
  JOIN dim_product p ON f.product_id = p.product_id
  WHERE f.order_date >= '2023-01-01'
  GROUP BY d.region_name, p.category_name
)
SELECT * FROM RegionalCohort WHERE rank_in_region <= 3;`,
      dax: `// Power BI DAX Calculated Measure for MoM Variance
MoM Sales Growth % = 
VAR CurrentSales = [Total Revenue]
VAR PreviousMonthSales = CALCULATE([Total Revenue], DATEADD('dim_date'[Date], -1, MONTH))
RETURN 
    DIVIDE(CurrentSales - PreviousMonthSales, PreviousMonthSales, 0)`,
      kpiStats: [
        { label: 'Gross Volume', value: '$1.48M', desc: '54,000+ transactional records audited' },
        { label: 'Profit Concentration', value: '62%', desc: 'Generated by top 18% corporate accounts' },
        { label: 'Delivery Latency Reduction', value: '22%', desc: 'Projected through regional stock rebalancing' }
      ]
    },
    'proj-2': {
      sql: `-- 2. Subscriber Cohort Churn Rate by Contract & Service Type
SELECT 
  contract_type,
  internet_service,
  COUNT(customer_id) AS cohort_size,
  SUM(CASE WHEN churn_flag = 1 THEN 1 ELSE 0 END) AS churn_count,
  ROUND(AVG(churn_flag) * 100, 2) AS churn_rate_pct,
  ROUND(AVG(monthly_charges), 2) AS avg_monthly_bill
FROM fact_telco_churn
GROUP BY contract_type, internet_service
HAVING COUNT(customer_id) > 100
ORDER BY churn_rate_pct DESC;`,
      dax: `// Power BI DAX for Customer Churn Rate
Customer Churn Rate % = 
VAR LostCustomers = CALCULATE(COUNTROWS('dim_customers'), 'dim_customers'[ChurnStatus] = "Yes")
VAR TotalCohort = COUNTROWS('dim_customers')
RETURN 
    DIVIDE(LostCustomers, TotalCohort, 0)`,
      kpiStats: [
        { label: 'Audited Profiles', value: '7,043', desc: 'Normalized and cleaned data schema' },
        { label: 'Fiber Attrition Rate', value: '42.7%', desc: 'Month-to-month contracts without support' },
        { label: 'Target Early Retention', value: '+14%', desc: 'Expected gain with 30-day automated onboarding' }
      ]
    },
    'proj-3': {
      sql: `-- 3. Inventory Stockout Risk & Reorder Priority List
SELECT 
  sku_code,
  item_description,
  current_stock,
  lead_time_days,
  avg_daily_demand,
  (lead_time_days * avg_daily_demand) AS safety_reorder_threshold,
  CASE 
    WHEN current_stock <= (lead_time_days * avg_daily_demand) * 0.5 THEN 'CRITICAL: Stockout Immediate'
    WHEN current_stock <= (lead_time_days * avg_daily_demand) THEN 'WARNING: Trigger Purchase Order'
    ELSE 'HEALTHY'
  END AS inventory_health_status
FROM fact_warehouse_inventory
WHERE current_stock <= (lead_time_days * avg_daily_demand)
ORDER BY (current_stock / NULLIF(avg_daily_demand, 0)) ASC;`,
      dax: `// Advanced Excel Nested Formula
=IF(D2<=(E2*F2)*0.5, "CRITICAL", IF(D2<=(E2*F2), "REORDER NOW", "HEALTHY"))`,
      kpiStats: [
        { label: 'Total Tracked SKUs', value: '1,200', desc: 'Automated warehouse stock movement' },
        { label: 'Stockout Prevention', value: '19%', desc: 'Mitigated stockout rate in peak demand' },
        { label: 'Report Time Saved', value: '6 hrs/wk', desc: 'Replaced manual ledger recalculations' }
      ]
    }
  };

  const currentDetails = deepDiveContent[project.id] || deepDiveContent['proj-1'];

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/85 backdrop-blur-sm overflow-hidden">
      <div className="relative w-full max-w-4xl max-h-[92dvh] sm:max-h-[88vh] bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden my-auto">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between p-4 sm:p-5 border-b border-slate-800 bg-slate-950 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-teal-950 border border-teal-500/40 flex items-center justify-center text-teal-400 shrink-0">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-mono text-teal-400 font-semibold">{project.category}</span>
                <span className="text-slate-600">·</span>
                <span className="text-[11px] text-slate-400">Deep Dive Analysis</span>
              </div>
              <h3 className="text-base sm:text-lg font-bold text-white leading-tight">
                {project.title}
              </h3>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selector */}
        <div className="flex items-center gap-2 px-4 sm:px-6 pt-3 border-b border-slate-800 bg-slate-950/60 overflow-x-auto scrollbar-none shrink-0">
          {[
            { id: 'overview', label: language === 'en' ? 'Overview & Scope' : 'सिंहावलोकन' },
            { id: 'sql', label: language === 'en' ? 'SQL Queries & DAX' : 'SQL व DAX लॉजिक' },
            { id: 'metrics', label: language === 'en' ? 'KPIs & Findings' : 'KPIs व निष्कर्ष' },
            { id: 'impact', label: language === 'en' ? 'Business ROI' : 'व्यावसायिक प्रभाव' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`pb-2.5 px-3 text-xs font-semibold border-b-2 transition-colors whitespace-nowrap cursor-pointer ${
                activeTab === tab.id
                  ? 'border-teal-400 text-teal-300'
                  : 'border-transparent text-slate-400 hover:text-white'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-4 sm:p-6 md:p-8 flex-1 overflow-y-auto overscroll-contain space-y-6 text-slate-200 text-xs sm:text-sm">
          
          {/* Tab 1: Overview */}
          {activeTab === 'overview' && (
            <div className="space-y-5">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {currentDetails.kpiStats.map((kpi, idx) => (
                  <div key={idx} className="p-3.5 bg-slate-950/80 rounded-xl border border-slate-800 space-y-1">
                    <span className="text-[11px] text-slate-400 block font-mono">{kpi.label}</span>
                    <span className="text-xl sm:text-2xl font-black text-teal-300">{kpi.value}</span>
                    <p className="text-[11px] text-slate-400">{kpi.desc}</p>
                  </div>
                ))}
              </div>

              <div className="p-4 bg-slate-950/60 rounded-xl border border-slate-800 space-y-2">
                <span className="font-bold text-teal-300 text-xs uppercase tracking-wider block">
                  {language === 'en' ? 'Problem Statement & Objective' : 'समस्या विवरण व उद्देश्य'}
                </span>
                <p className="text-slate-300 leading-relaxed">{project.problem}</p>
              </div>

              <div className="p-4 bg-slate-950/60 rounded-xl border border-slate-800 space-y-2">
                <span className="font-bold text-teal-300 text-xs uppercase tracking-wider block">
                  {language === 'en' ? 'Dataset & Analytical Process' : 'डेटासेट व विश्लेषण प्रक्रिया'}
                </span>
                <p className="text-slate-400 leading-relaxed mb-2 font-mono text-[11px]">{project.dataset}</p>
                <p className="text-slate-300 leading-relaxed">{project.process}</p>
              </div>

              <div className="flex flex-wrap gap-2 pt-2">
                <span className="text-xs text-slate-400 font-semibold mr-2 self-center">Tools Stack:</span>
                {project.tools.map((t) => (
                  <span key={t} className="px-2.5 py-1 rounded-lg bg-slate-800 text-teal-300 border border-slate-700 text-xs font-mono">
                    {t}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Tab 2: SQL & DAX */}
          {activeTab === 'sql' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="font-bold text-teal-300 text-xs flex items-center gap-1.5">
                  <Code2 className="w-4 h-4" />
                  <span>Production SQL Query Logic</span>
                </span>
                <button
                  onClick={() => handleCopyCode(currentDetails.sql)}
                  className="inline-flex items-center gap-1 text-[11px] text-slate-300 hover:text-white bg-slate-800 px-2.5 py-1 rounded border border-slate-700 cursor-pointer"
                >
                  {copied ? <Check className="w-3 h-3 text-teal-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied' : 'Copy Code'}</span>
                </button>
              </div>

              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 font-mono text-[11px] sm:text-xs overflow-x-auto text-teal-300/90 leading-relaxed">
                <pre><code>{currentDetails.sql}</code></pre>
              </div>

              <div className="pt-2">
                <span className="font-bold text-teal-300 text-xs flex items-center gap-1.5 mb-2">
                  <BarChart3 className="w-4 h-4" />
                  <span>Calculated Measure (DAX / Formula)</span>
                </span>
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 font-mono text-[11px] sm:text-xs text-emerald-300/90 overflow-x-auto">
                  <pre><code>{currentDetails.dax}</code></pre>
                </div>
              </div>
            </div>
          )}

          {/* Tab 3: Metrics & Insights */}
          {activeTab === 'metrics' && (
            <div className="space-y-4">
              <div className="p-4 bg-teal-950/40 border border-teal-500/40 rounded-xl space-y-2">
                <div className="flex items-center gap-2 text-teal-300 font-bold text-xs">
                  <TrendingUp className="w-4 h-4" />
                  <span>{language === 'en' ? 'Primary Data Discovery' : 'प्रमुख डेटा खोज'}</span>
                </div>
                <p className="text-slate-200 leading-relaxed text-sm">
                  {project.keyInsight}
                </p>
              </div>

              <div className="p-4 bg-slate-950/70 border border-slate-800 rounded-xl space-y-2">
                <span className="font-bold text-white text-xs uppercase tracking-wider block">
                  {language === 'en' ? 'Data Quality & Validation Audit' : 'डेटा सत्यापन व शुद्धता ऑडिट'}
                </span>
                <ul className="space-y-1.5 text-xs text-slate-300">
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-teal-400 shrink-0" />
                    <span>Null value imputation and removal of 200+ corrupted foreign keys.</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-teal-400 shrink-0" />
                    <span>Schema integrity verified with dimensional primary-foreign key relationships.</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-teal-400 shrink-0" />
                    <span>Cross-validated totals against source transactional ledgers.</span>
                  </li>
                </ul>
              </div>
            </div>
          )}

          {/* Tab 4: Impact & Recommendations */}
          {activeTab === 'impact' && (
            <div className="space-y-4">
              <div className="p-5 bg-slate-950/80 rounded-xl border border-slate-800 space-y-3">
                <span className="font-bold text-teal-300 text-xs uppercase tracking-wider block">
                  {language === 'en' ? 'Stakeholder Impact & Recommended Actions' : 'व्यावसायिक प्रभाव व सिफारिशें'}
                </span>
                <p className="text-slate-200 leading-relaxed text-sm">
                  {project.businessResult}
                </p>
              </div>

              <div className="p-4 bg-emerald-950/30 border border-emerald-500/30 rounded-xl text-xs text-emerald-200 space-y-1">
                <span className="font-bold text-emerald-300 block">Why this matters to hiring teams:</span>
                <p className="text-slate-300 leading-relaxed">
                  Demonstrates the full lifecycle of data analysis — from data hygiene and relational query architecture to executive-level business decision support.
                </p>
              </div>
            </div>
          )}

        </div>

        {/* Modal Footer */}
        <div className="p-3.5 sm:p-4 border-t border-slate-800 bg-slate-950 shrink-0 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <a
              href={project.githubUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-slate-300 hover:text-white bg-slate-900 border border-slate-800 rounded-lg hover:border-slate-700 transition-colors"
            >
              <FolderGit2 className="w-3.5 h-3.5 text-teal-400" />
              <span>GitHub Repo</span>
            </a>
            <a
              href={project.demoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-950 bg-teal-400 hover:bg-teal-300 rounded-lg transition-colors"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>Live Dashboard</span>
            </a>
          </div>

          <button
            onClick={onClose}
            className="px-4 py-1.5 text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors cursor-pointer"
          >
            {language === 'en' ? 'Close' : 'बंद करें'}
          </button>
        </div>

      </div>
    </div>
  );
};
